/*  3-30-MKR1010_create_thing
 *
 *
 * 
 * Components
 * ----------
 *  - MKR1010
 *
 *  Libraries
 *  ---------
 *  - None
 *
 * Connections
 * -----------
 *
 * - None
 *
 *
 *
 *  Created on March 4 2022 by Peter Dalmaris
 *
 */
/*
  Sketch generated by the Arduino IoT Cloud Thing "MKR1010 with OLED v2"
  https://create.arduino.cc/cloud/things/1ddbc18f-5e83-43b5-ab77-2a33177b5da6

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool led_on_off;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  pinMode(6,OUTPUT); // Set the LED pin as an output

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

}

void loop() {
  ArduinoCloud.update();
  // Your code here

}

/*
  Since LedOnOff is READ_WRITE variable, onLedOnOffChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedOnOffChange()  {
  // Add your code here to act upon LedOnOff change
  if (led_on_off){
    digitalWrite(6, HIGH);
    Serial.println("Button ON");
  } else
  {
    digitalWrite(6, LOW);
    Serial.println("Button OFF");
  }
}

void printValues() {
    Serial.print("Button: ");
    Serial.println(button);
    Serial.print("Pot: ");
    Serial.println(pot);

    Serial.print("Temperature = ");
    Serial.print(bme.readTemperature());
    Serial.println(" °C");
    temperature = bme.readTemperature(); // This will update the dashboard widget

    Serial.print("Pressure = ");
    Serial.print(bme.readPressure() / 100.0F);
    Serial.println(" hPa");
    pressure = bme.readPressure() / 100.0F; // This will update the dashboard widget

    Serial.print("Approx. Altitude = ");
    Serial.print(bme.readAltitude(SEALEVELPRESSURE_HPA));
    Serial.println(" m");

    Serial.print("Humidity = ");
    Serial.print(bme.readHumidity());
    Serial.println(" %");
    humidity = bme.readHumidity(); // This will update the dashboard widget


    Serial.println();
    update_oled();
}
