/*  4-60-Nano33iot
 *
 * Components
 * ----------
 *  - Arduino Nano 33 IoT
 *  - 1.3" OLED I2C SH1106
 *  - BME280 I2C
 *  - Button
 *  - Potentiometer
 *  - LED
 *
 *  Libraries
 *  ---------
 *  - arduino-timer.h
 *  - Adafruit_BME280.h
 *  - U8g2lib.h
 *
 * Connections
 * -----------
 *
 * See https://github.com/futureshocked/arduino_iot_cloud/blob/main/Wiring%20Schematics/Arduino%20Nano%2033%20IoT%20experiment.png
 *
 *
 *  Created on March 4 2022 by Peter Dalmaris
 *
 */

// arduino-timer - Version: Latest
#include <arduino-timer.h>

// U8g2 - Version: Latest
#include <U8g2lib.h>

// Adafruit BME280 Library - Version: Latest
#include <Adafruit_BME280.h>

/*
  Sketch generated by the Arduino IoT Cloud Thing "Nano 33 IoT v2"
  https://create.arduino.cc/cloud/things/4ad96e22-6882-46c6-858f-764ae38b62e6

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String message_one;
  float humidity;
  float mKR1010_Temperature;
  float pressure;
  float temperature;
  int led_pwm;
  int pot;
  bool button;
  bool led_on_off;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

#define SEALEVELPRESSURE_HPA (1013.25)
Adafruit_BME280 bme; // I2C

auto sensor_timer = timer_create_default(); // create a timer with default settings

bool get_sensor_readings(void *) {
  printValues();
  return true; // repeat? true
}

bool get_button_pot_state(void *) {
  pot = analogRead(6);
  button = digitalRead(15);
  Serial.print("button:");
  Serial.println(button);
  printValues();
  return true; // repeat? true
}

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  pinMode(10,OUTPUT); // Set the LED pin as an output
  pinMode(13,OUTPUT); // Set the LED pin as an output
  pinMode(15,INPUT_PULLUP);

  unsigned status;
  status = bme.begin(0x76);
  if (!status) {
        Serial.println("Could not find a valid BME280 sensor, check wiring, address, sensor ID!");
        Serial.print("SensorID was: 0x"); Serial.println(bme.sensorID(),16);
        Serial.print("        ID of 0xFF probably means a bad address, a BMP 180 or BMP 085\n");
        Serial.print("   ID of 0x56-0x58 represents a BMP 280,\n");
        Serial.print("        ID of 0x60 represents a BME 280.\n");
        Serial.print("        ID of 0x61 represents a BME 680.\n");
        while (1) delay(10);
    }

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  u8g2.begin();
  u8g2.clearBuffer();
  u8g2.setFont(u8g2_font_helvB18_tf);
  u8g2.drawStr(0, 30,"Starting...");
  u8g2.sendBuffer();

  sensor_timer.every(5000, get_sensor_readings);
  sensor_timer.every(500, get_button_pot_state);
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  sensor_timer.tick(); // tick the timer

}

/*
  Since MessageOne is READ_WRITE variable, onMessageOneChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMessageOneChange()  {
  // Add your code here to act upon MessageOne change
  update_oled();
}
/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}
/*
  Since Pressure is READ_WRITE variable, onPressureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPressureChange()  {
  // Add your code here to act upon Pressure change
}
/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}
/*
  Since LedPwm is READ_WRITE variable, onLedPwmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedPwmChange()  {
  // Add your code here to act upon LedPwm change
  analogWrite(10, led_pwm);
  Serial.println(led_pwm);
}
/*
  Since Pot is READ_WRITE variable, onPotChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPotChange()  {
  // Add your code here to act upon Pot change
}
/*
  Since Button is READ_WRITE variable, onButtonChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtonChange()  {
  // Add your code here to act upon Button change
}
/*
  Since LedOnOff is READ_WRITE variable, onLedOnOffChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedOnOffChange()  {
  // Add your code here to act upon LedOnOff change
  if (led_on_off){
    digitalWrite(13, HIGH);
    Serial.println("Button ON");
  } else
  {
    digitalWrite(13, LOW);
    Serial.println("Button OFF");
  }
}

void update_oled()
{
  u8g2.clearBuffer();
  u8g2.setFont(u8g2_font_luRS10_tf);
  u8g2.setFontPosTop();

  u8g2.setCursor(1, 5);
  u8g2.print(String(temperature,1) + (char)176 + "C");

  u8g2.setCursor(60, 5);
  u8g2.print(String(mKR1010_Temperature,1) + (char)176 + "C"); // This is a shared variable with the MKR1010 Thing

  u8g2.setCursor(1, 45);
  u8g2.print(pot);

  u8g2.setCursor(40, 45);
  u8g2.print(message_one);

  u8g2.setCursor(1, 25);
  u8g2.print(String(pressure) + "hPa");

  u8g2.setCursor(85, 25);
  u8g2.print(String(humidity,1) + "%");

  u8g2.setCursor(110, 5);
    if (button)
      u8g2.print("O");
    else
      u8g2.print("|");
  u8g2.sendBuffer();
  onLedOnOffChange();
}

void printValues() {
    Serial.print("Temperature = ");
    Serial.print(bme.readTemperature());
    Serial.println(" °C");
    temperature = bme.readTemperature(); // This will update the dashboard widget

    Serial.print("Pressure = ");
    Serial.print(bme.readPressure() / 100.0F);
    Serial.println(" hPa");
    pressure = bme.readPressure() / 100.0F; // This will update the dashboard widget

    Serial.print("Approx. Altitude = ");
    Serial.print(bme.readAltitude(SEALEVELPRESSURE_HPA));
    Serial.println(" m");

    Serial.print("Humidity = ");
    Serial.print(bme.readHumidity());
    Serial.println(" %");
    humidity = bme.readHumidity(); // This will update the dashboard widget

    Serial.println();
    update_oled();
}

/*
  Since MKR1010Temperature is READ_WRITE variable, onMKR1010TemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMKR1010TemperatureChange()  {
  // Add your code here to act upon MKR1010Temperature change

}
